sqlcounter max_connections {
    counter_name = max_connections
    check_name = Simultaneous-Use
    sql_module_instance = sql
    key = User-Name
    reset = never
    query = "SELECT COUNT(*) FROM radacct WHERE username = '%{${key}}' AND acctstoptime IS NULL"
}
