eap-radius {
    class_group = yes
    servers {
        radius {
            address = radius
            secret = @@RADIUS_SECRET@@
            auth_port = 1812
            acct_port = 1813
            nas_identifier = strongswan
        }
    }
    xauth {
        ignore = no
    }
    forward_ike = yes
    accounting = yes
    accounting_interval = 0
    close_all_on_timeout = yes
    eap_start = yes
}
