system:
  appid: StrongSwanVPN
  location: Europe/Moscow
  workdir: /data
  debug: false

database:
  type: sqlite
  name: /data/toughradius.db

radiusd:
  enabled: true
  host: 0.0.0.0
  auth_port: 1812
  acct_port: 1813
  debug: true

logger:
  mode: development
  file_enable: false

web:
  host: 0.0.0.0
  port: 1816
  secret: "${TOUGHRADIUS_WEB_SECRET:-change-me-to-a-random-value-32}"

sys_config:
  radius.EapMethod: eap-mschapv2
  radius.EapEnabledHandlers: eap-md5,eap-mschapv2
