# /etc/strongswan.conf
charon {
    load_modular = yes

    filelog {
        charon {
            path = /var/log/charon.log
            flush_line = yes
            default = 1
            ike = 2
            cfg = 1
        }
    }

    plugins {
        include strongswan.d/charon/*.conf

        eap-radius {
            accounting = yes
            servers {
                primary {
                    address = 127.0.0.1
                    auth_port = 1812
                    acct_port = 1813
                    secret = HpE98gAFA4OaJaHYU46M
                    nas_identifier = strongSwan
                }
            }
        }
    }
}
