# /etc/strongswan.conf
charon {
    load_modular = yes
    plugins {
        include strongswan.d/charon/*.conf

        vici {

        }

        eap-radius {
            server = ${env:RADIUS_ADDR}
            secret = ${env:RADIUS_SECRET}
            accounting = yes
        }
    }
}
