# /etc/strongswan.conf
charon {
    load_modular = yes

    filelog {
        charon {
            path = /var/log/charon.log
            flush_line = yes
            default = 2
            ike = 2
            cfg = 2
            mgr = 2
            net = 2
        }
        stderr {
            ike = 2
            knl = 3
        }
    }

    plugins {
        include strongswan.d/charon/*.conf

        vici {

        }

        eap-radius {
            server = 127.0.0.1:1812
            secret = HpE98gAFA4OaJaHYU46M
            accounting = yes
        }
    }
}
