charon {
    load_modular = yes
    plugins {
        include /etc/strongswan.d/charon/*.conf
        vici {
            socket = unix:///var/run/charon.vici
        }
        eap-radius {
            servers {
                radius {
                    address = radius
                    secret = @@RADIUS_SECRET@@
                    auth_port = 1812
                    acct_port = 1813
                }
            }
            forward_ike = yes
            accounting = yes
            eap_start = yes
        }
    }
}
